/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddList: typeof import('./src/components/AddList.vue')['default']
    CanvasEdit: typeof import('./src/components/CanvasEdit.vue')['default']
    ComponentList: typeof import('./src/components/ComponentList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ItemBox: typeof import('./src/components/ItemBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowList: typeof import('./src/components/ShowList.vue')['default']
    TestComp: typeof import('./src/components/TestComp.vue')['default']
  }
}
